### ISSUE TITLE
InsecureRequestWarning

### ISSUE THREAD

**Issue by sec13b** [Ridter/owa_info#2]
can you add this line , 
from urllib3.exceptions import InsecureRequestWarning
from urllib3 import disable_warnings
disable_warnings(InsecureRequestWarning)

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
python --version
Python 3.11.2
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

python owa_info.py -u https://192.168.1.10
/usr/lib/python3/dist-packages/urllib3/connectionpool.py:1048: InsecureRequestWarning: Unverified HTTPS request is being made to host 'docs.microsoft.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
/usr/lib/python3/dist-packages/urllib3/connectionpool.py:1048: InsecureRequestWarning: Unverified HTTPS request is being made to host 'learn.microsoft.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
/usr/lib/python3/dist-packages/urllib3/connectionpool.py:1048: InsecureRequestWarning: Unverified HTTPS request is being made to host 'learn.microsoft.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
[*] Try to access https://docs.microsoft.com/en-us/exchange/new-features/build-numbers-and-release-dates
[*] Checking https://192.168.1.10

**Comment by Ridter** [comment]
done.
