### ISSUE TITLE
sl.wrap_socket() is deprecated

### ISSUE THREAD

**Issue by sec13b** [Ridter/owa_info#3]
can you help with this , thank you

/home/kali/Desktop/owa_info/owa_info.py:278: DeprecationWarning: ssl.wrap_socket() is deprecated, use SSLContext.wrap_socket()
  ssl_sock = ssl.wrap_socket(s, ca_certs=None)

**Comment by sec13b** [comment]
Line 276 edit who need.

#ssl_sock = ssl.wrap_socket(s, ca_certs=None)
ssl_sock = ssl.wrap_socket(s, ca_certs=None)

**Comment by Ridter** [comment]
👍
